syntax = "proto3";

package ru.belikoooova.dvs.blockchain.service.grpc.v1;

service BlockchainService {
  rpc SaveVote(SaveVoteRequest) returns (SaveVoteResponse);
  rpc GetBlock(GetBlockRequest) returns (GetBlockResponse);
  rpc GetAllBlocks(GetAllBlockRequest) returns (GetAllBlocksResponse);
}

message SaveVoteRequest {
  string voteId = 1;
  string userId = 2;
  string encryptedVote = 3;
  string zeroKnowledgeProof = 4;
}

message SaveVoteResponse {
  string voteToken = 1;
}

message GetBlockRequest {
  string voteToken = 1;
}

message GetBlockResponse {
  string voteId = 1;
  string userId = 2;
  string voteToken = 3;
  string encryptedVote = 4;
  string zeroKnowledgeProof = 5;
  int64 timestamp = 6;
  string blockHash = 7;
}

message GetAllBlockRequest {
  string votingId = 1;
}

message GetAllBlocksResponse {
  repeated GetBlockResponse blocks = 1;
}