openapi: 3.0.3

info:
  title: Cryptography Service
  description: |-
    Документация API
  version: v1

tags:
  - name: Cryptography
    description: Шифрование, проверка, подпись

paths:
  /crypto/api/v1/sign:
    post:
      tags:
        - Cryptography
      summary: Подпись ключа для голосования
      description: Подпись ключа для голосования
      operationId: Sign
      parameters:
        - in: header
          name: X-User-Id
          schema:
            type: string
          description: ID пользователя
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignRequest'
        required: true
      responses:
        200:
          description: Регистрация успешна
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignResponse'
        400:
          description: Некорректные параметры запроса
  /crypto/api/v1/publicKey:
    get:
      tags:
        - Cryptography
      summary: Получение публичного ключа системы
      description: Получение публичного ключа системы
      operationId: GetSystemPublicKey
      parameters:
        - in: header
          name: X-User-Id
          schema:
            type: string
          description: ID пользователя
          required: true
      responses:
        200:
          description: Регистрация успешна
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicKeyResponse'
        400:
          description: Некорректные параметры запроса
  /crypto/api/v1/votings/{votingId}/zeroKnowledgeProof:
    get:
      tags:
        - Cryptography
      summary: Генерация доказательства с нулевым разглашением для голосования
      description: Генерация доказательства с нулевым разглашением для голосования
      operationId: GetZeroKnowledgeProof
      parameters:
        - in: path
          name: votingId
          schema:
            type: string
          required: true
        - in: header
          name: X-User-Id
          schema:
            type: string
          description: ID пользователя
          required: true
      responses:
        200:
          description: Запрос отправлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZeroKnowledgeProofResponse'
        400:
          description: Некорректные параметры запроса

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    SignRequest:
      type: object
      properties:
        blindedPublicKey:
          type: string
      required:
        - blindedPublicKey
    SignResponse:
      type: object
      properties:
        blindSignature:
          type: string
      required:
        - blindSignature
    PublicKeyResponse:
      type: object
      properties:
        publicKey:
          type: string
      required:
        - publicKey
    ZeroKnowledgeProofResponse:
      type: object
      properties:
        zeroKnowledgeProof:
          type: string
      required:
        - zeroKnowledgeProof