version=1.0.0-SNAPSHOT

spring-boot-version=3.4.3
dependency-management-version=1.1.7
openapi-plugin-version=7.8.0
jjwt-version=0.11.5
jpa-version=1.9.25
grpc-server-spring-boot-starter-version=3.1.0.RELEASE
grpc-client-spring-boot-starter-version=3.1.0.RELEASE
javax-annotation-api-version=1.3.2
grpc-version=1.37.0
protoc-gen-grpc-java-version=1.37.0
protobuf-version=3.25.1
protobuf-plugin-version=0.9.1
protoc-gen-grpc-kotlin-version=1.4.0
kotlin-stub-version=1.2.0
swagger-version=2.2.22
liquibase-plugin-version=2.2.2
envoy-version=1.0.44