syntax = "proto3";

package ru.belikoooova.voting.system.grpc.v1;

option java_package = "ru.belikoooova.voting.system.grpc.v1";

service CryptoService {
  rpc checkSign(CheckSignRequest) returns (CheckResponse);
  rpc checkZeroKnowledgeProof(CheckZeroKnowledgeProofRequest) returns (CheckResponse);
}

message CheckSignRequest {
  string signedPublicKey = 1;
  string originalMessage = 2;
}

message CheckResponse {
  bool valid = 1;
  string message = 2;
}

message CheckZeroKnowledgeProofRequest {
  string encryptedVote = 1;
  string zkProof = 2;
}
