---
name: auth
services:
  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      interval: 10s
      timeout: 3s
      retries: 12
  envoy:
    image: envoyproxy/envoy:v1.25.0
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "debug"]
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"